# Step 1: Build the app
FROM node:23.5.0-alpine AS builder


WORKDIR /app

# Copy package.json and package-lock.json first to take advantage of Docker caching
COPY package.json package-lock.json ./

# Install dependencies (use only production dependencies for the final image)
RUN npm install

# Copy the rest of the app
COPY . .

# Build the Next.js app for production
RUN npm run build

# Step 2: Create the production image
FROM node:23.5.0-alpine AS builder


WORKDIR /app

# Copy necessary files from the builder
COPY --from=builder /app/package.json /app/package-lock.json /app/.next /app/public /app/

# Install production dependencies
RUN npm install --production

# Expose port
EXPOSE 3000

# Run the Next.js app
CMD ["npm", "start"]